# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13ad57cd5dabca4ea87f29f6cea6fa4d242dfa71e04bac96c622258c01c5094778b909939cfc280890159d1ed4219128fbf5a76127ea5d394e2be2618cbfb1f3

test:
  secret_key_base: e542889bdd720e2c3981c0b97f1a7bf802a0a4be694bed65b677d2feb9be89ad772ce90d54e84ef03076b30da23eff43a4f98af726d2f9ff79ef36cc6fe2b5d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
